Repository qiskit-community/qiskit-machine-learning, pull requests merged in 2021-09, with the labels that each got.

#206 Improve project setup long-description & Ignore untagged release notes on docs.upload
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
  CODE_OF_CONDUCT.md
  README.md
  setup.py
  tools/ignore_untagged_notes.sh
Labels: type: enhancement, type: documentation

#207 [Stable] Improve project setup long-description & Ignore untagged release notes on docs.upload (#206)
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
  CODE_OF_CONDUCT.md
  README.md
  setup.py
  tools/ignore_untagged_notes.sh
Labels: type: enhancement, type: documentation

#211 Replace calls to the `optimize` method with the corresponding `minimize`
  qiskit_machine_learning/algorithms/classifiers/neural_network_classifier.py
  qiskit_machine_learning/algorithms/distribution_learners/qgan/numpy_discriminator.py
  qiskit_machine_learning/algorithms/distribution_learners/qgan/quantum_generator.py
  qiskit_machine_learning/algorithms/regressors/neural_network_regressor.py
  qiskit_machine_learning/algorithms/trainable_model.py
Labels: priority: low, type: enhancement

#222 Disable pylint consider-using-f-string for now
  .pylintrc
Labels: priority: high, type: bug

#229 Re-enable lint f-string check
  .pylintrc
  README.md
  qiskit_machine_learning/algorithms/classifiers/vqc.py
  qiskit_machine_learning/algorithms/distribution_learners/qgan/qgan.py
  qiskit_machine_learning/deprecation.py
  qiskit_machine_learning/kernels/quantum_kernel.py
  qiskit_machine_learning/version.py
  test/algorithms/classifiers/test_neural_network_classifier.py
  test/connectors/test_hybrid_connector.py
  test/connectors/test_torch_connector.py
  test/machine_learning_test_case.py
  test/neural_networks/test_circuit_qnn.py
  test/test_readme_sample.py
  tools/check_copyright.py
  tools/extract_deprecation.py
  tools/generate_spell_dict.py
  tools/verify_headers.py
Labels: type: qa

#234 Fixing the translations script that was breaking the translated docs publish build
  tools/deploy_translatable_strings.sh
Labels: stable backport potential, automerge
