Repository qiskit-community/qiskit-machine-learning, pull requests merged in 2021-05, with the labels that each got.

#77 Fix qGAN gradient behavior
  qiskit_machine_learning/algorithms/distribution_learners/qgan/quantum_generator.py
  releasenotes/notes/qgan_gradient_fix-6d2dd8f1b471d8c0.yaml
  test/algorithms/distribution_learners/qgan/test_qgan.py
Labels: Changelog: Bugfix

#86 Add git blame ignore file
  .git-blame-ignore-revs
  CONTRIBUTING.md
Labels: type: qa

#85 Insert actual path to source when generating docs
  docs/conf.py
Labels: type: documentation

#89 Fix sphinx CI Error
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
Labels: automerge, priority: high, stable backport potential, type: ci

#91 [Stable] Fix sphinx CI Error (#89)
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
Labels: type: ci

#88 Add seed to test torch connector & change accuracy readme test
  test/connectors/test_torch_connector.py
  test/test_readme_sample.py
Labels: priority: high, type: bug

#103 Make sparse dependency optional
  .github/actions/install-machine-learning/action.yml
  .github/workflows/main.yml
  .pylintdict
  qiskit_machine_learning/algorithms/objective_functions.py
  qiskit_machine_learning/connectors/torch_connector.py
  qiskit_machine_learning/neural_networks/circuit_qnn.py
  qiskit_machine_learning/neural_networks/neural_network.py
  qiskit_machine_learning/neural_networks/opflow_qnn.py
  qiskit_machine_learning/neural_networks/sampling_neural_network.py
  requirements.txt
  setup.py
  test/neural_networks/test_circuit_qnn.py
Labels: priority: medium, type: enhancement

#106 Apply spell check to tutorials
  .pylintdict
  Makefile
  docs/Makefile
  docs/conf.py
  docs/lowercase_filter.py
  docs/tutorials/01_neural_networks.ipynb
  docs/tutorials/03_quantum_kernel.ipynb
  releasenotes/notes/caching-and-trainable-model-37b7de903bd163ff.yaml
  requirements-dev.txt
  tools/generate_spell_dict.py
Labels: type: documentation

#108 Run tutorials from stable branch
  .github/workflows/main.yml
  Makefile
  docs/Makefile
Labels: type: ci
