Repository qiskit-community/qiskit-machine-learning, pull requests merged in 2021-07, with the labels that each got.

#145 Update deprecate methods and deploy doc to be the same as other repos
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
  .gitignore
  docs/versionutils.py
  qiskit_machine_learning/deprecation.py
  test/test_deprecation.py
  tools/deploy_translatable_strings.sh
Labels: priority: critical, type: bug

#146 Fix/Update TorchConnector tutorial
  docs/tutorials/05_torch_connector.ipynb
  qiskit_machine_learning/connectors/torch_connector.py
  qiskit_machine_learning/neural_networks/circuit_qnn.py
  qiskit_machine_learning/neural_networks/opflow_qnn.py
  qiskit_machine_learning/neural_networks/sampling_neural_network.py
  qiskit_machine_learning/neural_networks/two_layer_qnn.py
  releasenotes/notes/fix-hybrid-batch-gradient-325331b80a020748.yaml
Labels: Changelog: Bugfix, type: documentation

#154 Pin networkx
  requirements-dev.txt
Labels: priority: critical, stable backport potential, type: bug

#152 Updating the translation deploy script
  docs/conf.py
  tools/deploy_translatable_strings.sh
Labels: stable backport potential

#162 Streamline CI
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
Labels: type: ci, type: enhancement

#163 Cancels previous running workflows
  .github/workflows/cancel.yml
Labels: type: ci, type: enhancement

#151 This adds the callback feature for NN Classifier and Regressor (#112)
  qiskit_machine_learning/algorithms/classifiers/neural_network_classifier.py
  qiskit_machine_learning/algorithms/classifiers/vqc.py
  qiskit_machine_learning/algorithms/regressors/neural_network_regressor.py
  qiskit_machine_learning/algorithms/regressors/vqr.py
  qiskit_machine_learning/algorithms/trainable_model.py
  releasenotes/notes/callback-for-NN-classifier-regressor-8e1d5c887335e6d9.yaml
  test/algorithms/classifiers/test_neural_network_classifier.py
  test/algorithms/regressors/test_neural_network_regressor.py
Labels: Changelog: New Feature

#164 Use concurrency group to cancel previous workflow
  .github/workflows/cancel.yml
  .github/workflows/main.yml
Labels: type: ci, type: enhancement

#143 Added ability to automatically handle categorical labels (#62)
  qiskit_machine_learning/algorithms/classifiers/neural_network_classifier.py
  releasenotes/notes/cateforical-output-049e682adc9d1e28.yaml
  test/algorithms/classifiers/test_neural_network_classifier.py
Labels: Changelog: New Feature

#166 [Stable] Streamline CI
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
Labels: type: ci, type: enhancement

#165 Exclude locale from the sync path
  tools/deploy_documentation.sh
Labels: automerge, stable backport potential

#169 Torch Module fails to import on sphinx >= 4.1.0
  docs/conf.py
  requirements-dev.txt
Labels: stable backport potential, type: bug, type: documentation

#160 Preparing to publish translated Qiskit ML Documentation
  docs/versionutils.py
Labels: automerge, stable backport potential

#172 Add link to repo tutorial on html tutorial prolog
  docs/conf.py
Labels: stable backport potential, type: documentation, type: enhancement

#174 Qiskit/qiskit#1303 change Markdown link to reStructuredText syntax
  docs/getting_started.rst
Labels: type: documentation
