Repository qiskit-community/qiskit-machine-learning, pull requests merged in 2021-08, with the labels that each got.

#183 Bump reno requirement to latest version and set default_branch
  releasenotes/config.yaml
  requirements-dev.txt
Labels: automerge, stable backport potential

#186 Preparing to publish Bengali, French and Hindi ML docs
  docs/versionutils.py
Labels: stable backport potential, type: enhancement, type: documentation, automerge

#189 Fix lint errors
  qiskit_machine_learning/algorithms/distribution_learners/qgan/qgan.py
  qiskit_machine_learning/version.py
  test/datasets/test_breast_cancer.py
  test/datasets/test_digits.py
  test/datasets/test_iris.py
  test/datasets/test_wine.py
  tools/extract_deprecation.py
  tools/generate_spell_dict.py
Labels: priority: high, stable backport potential, type: bug

#191 Fix docs release notes search
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
  Makefile
Labels: priority: high, type: documentation

#192 [Stable] Fix docs release notes search (#191)
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
  Makefile
Labels: priority: high, type: documentation

#182 Fix `RawFeatureVector` copy
  qiskit_machine_learning/circuit/library/raw_feature_vector.py
  releasenotes/notes/fix-raw-feature-vector-copy-20534d595a0056de.yaml
  test/circuit/library/test_raw_feature_vector.py
Labels: Changelog: Bugfix
