Repository qiskit-community/qiskit-machine-learning, pull requests merged in 2021-06, with the labels that each got.

#99 Remove Backend Deprecate Messages
  docs/tutorials/01_neural_networks.ipynb
  docs/tutorials/02_neural_network_classifier_and_regressor.ipynb
  docs/tutorials/05_torch_connector.ipynb
  test/algorithms/classifiers/test_neural_network_classifier.py
  test/algorithms/classifiers/test_qsvc.py
  test/algorithms/classifiers/test_vqc.py
  test/algorithms/regressors/test_neural_network_regressor.py
  test/algorithms/regressors/test_qsvr.py
  test/algorithms/regressors/test_vqr.py
  test/circuit/library/test_raw_feature_vector.py
  test/connectors/test_torch_connector.py
  test/kernels/test_qkernel.py
  test/neural_networks/test_circuit_qnn.py
  test/neural_networks/test_opflow_qnn.py
  test/neural_networks/test_two_layer_qnn.py
Labels: type: enhancement

#121 Fixes batch gradient computation in TorchConnector
  .pylintdict
  qiskit_machine_learning/connectors/torch_connector.py
  releasenotes/notes/fix-batch-gradients-1eb2332cc2082c57.yaml
  test/connectors/test_torch_connector.py
Labels: Changelog: Bugfix

#111 Replace the `weights` property in the pytorch connector with `weight`
  qiskit_machine_learning/connectors/torch_connector.py
  releasenotes/notes/pytorch-weight-property-81105bfd5250efe0.yaml
Labels: priority: low, type: enhancement

#122 Docs - Remove non overidden base methods/attributes from classes
  docs/_templates/autosummary/class.rst
Labels: type: documentation

#123 Add loss functions to docs
  .pylintdict
  docs/apidocs/qiskit_machine_learning.utils.loss_functions.rst
  docs/apidocs/qiskit_machine_learning.utils.rst
  qiskit_machine_learning/__init__.py
  qiskit_machine_learning/utils/__init__.py
Labels: type: documentation

#64 Extend docstrings of loss functions
  .pylintdict
  qiskit_machine_learning/algorithms/objective_functions.py
  qiskit_machine_learning/utils/loss_functions/loss_functions.py
  test/utils/loss_functions/test_loss_functions.py
Labels: type: documentation

#125 Add deprecation method template
  qiskit_machine_learning/algorithms/classifiers/qsvc.py
  qiskit_machine_learning/algorithms/distribution_learners/qgan/numpy_discriminator.py
  qiskit_machine_learning/algorithms/distribution_learners/qgan/pytorch_discriminator.py
  qiskit_machine_learning/algorithms/regressors/qsvr.py
  qiskit_machine_learning/connectors/torch_connector.py
  qiskit_machine_learning/deprecation.py
  qiskit_machine_learning/kernels/quantum_kernel.py
  test/connectors/test_torch_connector.py
  test/test_deprecation.py
Labels: type: enhancement

#134 Add deprecate_values decorator
  .github/workflows/main.yml
  qiskit_machine_learning/deprecation.py
  test/test_deprecation.py
Labels: type: enhancement

#135 Fixups to API ref documentation
  docs/apidocs/qiskit_machine_learning.connectors.rst
  qiskit_machine_learning/__init__.py
  qiskit_machine_learning/connectors/torch_connector.py
  qiskit_machine_learning/neural_networks/__init__.py
  qiskit_machine_learning/neural_networks/circuit_qnn.py
  qiskit_machine_learning/neural_networks/neural_network.py
  qiskit_machine_learning/neural_networks/opflow_qnn.py
  qiskit_machine_learning/neural_networks/two_layer_qnn.py
Labels: type: documentation

#136 [Stable] Add Getting Started Documentation & Preparing ML docs & tutorials for translations
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
  README.md
  docs/_templates/versions.html
  docs/conf.py
  docs/custom_directives.py
  docs/getting_started.rst
  docs/index.rst
  docs/versionutils.py
  requirements-dev.txt
  tools/deploy_translatable_strings.sh
  tools/github_poBranch_update_key.enc
  tox.ini
Labels: type: documentation

#137 Fix bugs from PR #130
  .github/workflows/deploy-docs.yml
  tools/deploy_translatable_strings.sh
Labels: stable backport potential

#138 [Stable] Fix bugs from PR #130 (#137)
  .github/workflows/deploy-docs.yml
  tools/deploy_translatable_strings.sh
Labels: type: documentation

#140 Fix deploy docs github action
  .github/workflows/deploy-docs.yml
Labels: type: bug, type: documentation
