Repository qiskit-community/qiskit-machine-learning, pull requests merged in 2022-03, with the labels that each got.

#337 Bump black version and relax constraint
  qiskit_machine_learning/algorithms/distribution_learners/qgan/quantum_generator.py
  qiskit_machine_learning/circuit/library/raw_feature_vector.py
  qiskit_machine_learning/datasets/ad_hoc.py
  qiskit_machine_learning/datasets/dataset_helper.py
  qiskit_machine_learning/neural_networks/circuit_qnn.py
  requirements-dev.txt
Labels: type: enhancement

#338 Adopt lazy imports from Terra
  qiskit_machine_learning/algorithms/distribution_learners/qgan/_pytorch_discriminator_net.py
  qiskit_machine_learning/algorithms/distribution_learners/qgan/numpy_discriminator.py
  qiskit_machine_learning/algorithms/distribution_learners/qgan/pytorch_discriminator.py
  qiskit_machine_learning/algorithms/objective_functions.py
  qiskit_machine_learning/connectors/torch_connector.py
  qiskit_machine_learning/datasets/ad_hoc.py
  qiskit_machine_learning/datasets/breast_cancer.py
  qiskit_machine_learning/datasets/digits.py
  qiskit_machine_learning/datasets/gaussian.py
  qiskit_machine_learning/datasets/iris.py
  qiskit_machine_learning/datasets/wine.py
  qiskit_machine_learning/neural_networks/circuit_qnn.py
  qiskit_machine_learning/neural_networks/neural_network.py
  qiskit_machine_learning/neural_networks/opflow_qnn.py
  qiskit_machine_learning/neural_networks/sampling_neural_network.py
  qiskit_machine_learning/optionals.py
  qiskit_machine_learning/runtime/torch_runtime_client.py
  requirements.txt
  test/__init__.py
  test/algorithms/distribution_learners/qgan/test_qgan.py
  test/connectors/test_hybrid_connector.py
  test/connectors/test_torch_connector.py
  test/kernels/algorithms/test_qkernel_trainer.py
  test/machine_learning_test_case.py
  test/neural_networks/test_circuit_qnn.py
  test/neural_networks/test_opflow_qnn.py
  test/runtime/test_torch_runtime_client.py
  test/utils/loss_functions/test_loss_functions.py
Labels: type: enhancement, run_slow

#343 Add extra installs to tox
  tox.ini
Labels: type: enhancement, automerge, type: ci

#345 Quantum kernel fix for dimensions other than 2
  qiskit_machine_learning/kernels/quantum_kernel.py
  releasenotes/notes/fix-quantum-kernel-n-dimensions-a2a446c5a1f463ea.yaml
  test/algorithms/classifiers/test_pegasos_qsvc.py
Labels: Changelog: Bugfix, stable backport potential

#346 Add test decorator 'gpu' for GPU unit tests
  .pylintdict
  test/__init__.py
  test/machine_learning_test_case.py
  tools/find_gpu_decorated_methods.py
  tox.ini
Labels: type: enhancement, type: ci

#351 Remove the deprecated weights property in favor of weight in TorchConnector
  qiskit_machine_learning/connectors/torch_connector.py
  test/connectors/test_torch_connector.py
Labels: type: enhancement

#353 Pin Jinja2 used by Sphinx
  requirements-dev.txt
Labels: priority: high, stable backport potential, type: bug, type: documentation, automerge

#355 Fix GPU Unit Test name
  test/connectors/test_gpu_torch_networks.py
  tools/find_gpu_decorated_methods.py
Labels: type: bug, automerge, type: ci

#359 Add apply fixes to copyright checker
  .github/workflows/main.yml
  tools/check_copyright.py
Labels: type: enhancement, automerge, type: qa, type: ci
