Repository qiskit-community/qiskit-machine-learning, pull requests merged in 2022-08, with the labels that each got.

#449 Automatically set docs current year
  docs/conf.py
Labels: stable backport potential, type: documentation, automerge

#452 Enable inter-documentation links to be clickable
  docs/conf.py
Labels: stable backport potential, type: documentation

#443 Delay gradient operator initialization
  qiskit_machine_learning/neural_networks/circuit_qnn.py
  qiskit_machine_learning/neural_networks/opflow_qnn.py
  releasenotes/notes/delay-gradient-initialization-ae00dd14cc325a2c.yaml
  test/neural_networks/test_circuit_qnn.py
  test/neural_networks/test_opflow_qnn.py
Labels: Performance

#462 Quantum Convolutional Neural Network
  .pylintdict
  docs/tutorials/11_quantum_convolutional_neural_networks.ipynb
Labels: stable backport potential, documentation

#465 fix typo CNN -> CCNN in 11_quantum_convolutional_neural_networks.ipynb
  docs/tutorials/11_quantum_convolutional_neural_networks.ipynb
Labels: stable backport potential, documentation, Community PR
