Repository qiskit-community/qiskit-machine-learning, pull requests merged in 2022-07, with the labels that each got.

#435 Add missing underscore in the 09 tutorial file name
  docs/tutorials/09_saving_and_loading_models.ipynb
Labels: documentation

#438 Script to check if reno release note was committed to the wrong place
  Makefile
  tools/find_stray_release_notes.py
  tox.ini
Labels: type: qa, type: ci

#440 Run tox cuda unit tests in a single serial process
  tox.ini
Labels: type: ci

#442 Fix SVCLoss docstring
  .pylintdict
  qiskit_machine_learning/utils/loss_functions/kernel_loss_functions.py
Labels: type: documentation
