Repository qiskit-community/qiskit-machine-learning, pull requests merged in 2022-12, with the labels that each got.

#536 Remove unnecessary networkx requirement
  requirements-dev.txt
Labels: stable backport potential, automerge, type: ci

#515 Improved content for Tutorial 3 (QAMP fall'22)
  .pylintdict
  docs/tutorials/03_quantum_kernel.ipynb
Labels: QAMP

#541 Fix code block in getting started page
  docs/getting_started.rst
Labels: stable backport potential, documentation

#542 Update tox configuration for tox 4.0.2
  test/kernels/algorithms/test_qkernel_trainer.py
  test/kernels/test_qkernel.py
  tox.ini
Labels: stable backport potential, automerge, type: ci

#545 Tox: pass parent env.variables to tox on gpu unit tests
  tox.ini
Labels: automerge, type: ci
