Repository qiskit-community/qiskit-machine-learning, pull requests merged in 2022-02, with the labels that each got.

#304 Fix quantum kernel trainer web docs
  docs/apidocs/qiskit_machine_learning.kernels.algorithms.rst
  qiskit_machine_learning/kernels/__init__.py
  qiskit_machine_learning/kernels/algorithms/__init__.py
Labels: stable backport potential, type: documentation

#309 Use code from README.md in test_readme_sample
  README.md
  test/test_readme_sample.py
Labels: stable backport potential, type: enhancement, type: ci

#312 Fix VQC training with warm_start=True
  qiskit_machine_learning/algorithms/trainable_model.py
  releasenotes/notes/fix-vqc-warm-start-1c15d3f5742c5e84.yaml
  test/algorithms/classifiers/test_vqc.py
Labels: Changelog: Bugfix, stable backport potential

#319 Deprecate some dataset functions
  README.md
  qiskit_machine_learning/datasets/breast_cancer.py
  qiskit_machine_learning/datasets/digits.py
  qiskit_machine_learning/datasets/gaussian.py
  qiskit_machine_learning/datasets/iris.py
  qiskit_machine_learning/datasets/wine.py
  releasenotes/notes/deprecate-datasets-a2337ca0238faebb.yaml
  test/datasets/__init__.py
  test/datasets/test_breast_cancer.py
  test/datasets/test_digits.py
  test/datasets/test_gaussian.py
  test/datasets/test_iris.py
  test/datasets/test_wine.py
Labels: type: enhancement

#317 fixes #297: fitting in batches without all labels
  qiskit_machine_learning/algorithms/classifiers/vqc.py
  releasenotes/notes/fix-batching-with-incomplete-labels-2fcf26585903d437.yaml
  test/algorithms/classifiers/test_vqc.py
Labels: stable backport potential

#324 [Stable] Prepare 0.3.1 release
  qiskit_machine_learning/VERSION.txt
Labels: automerge
