Repository qiskit-community/qiskit-machine-learning, pull requests merged in 2022-06, with the labels that each got.

#409 Add .editorconfig
  .editorconfig
Labels: type: qa

#417 Add missing instructions for docs. build
  CONTRIBUTING.md
Labels: type: enhancement, type: documentation, automerge

#416 Add overview to docs
  README.md
  docs/index.rst
Labels: stable backport potential, type: enhancement, type: documentation

#424 Fix FakeToronto import and Fix Aer Deprecate Messages
  test/algorithms/classifiers/test_neural_network_classifier.py
  test/algorithms/classifiers/test_vqc.py
  test/algorithms/regressors/test_neural_network_regressor.py
  test/algorithms/regressors/test_vqr.py
  test/circuit/library/test_raw_feature_vector.py
  test/connectors/test_torch.py
  test/neural_networks/test_circuit_qnn.py
  test/neural_networks/test_effective_dimension.py
  test/neural_networks/test_opflow_qnn.py
  test/neural_networks/test_two_layer_qnn.py
Labels: priority: high, type: ci

#427 switched to sphinx-design
  docs/conf.py
  docs/getting_started.rst
  requirements-dev.txt
Labels: stable backport potential, type: documentation, automerge

#419 Grammar mistake in 07_pegasos_qsvc.ipynb
  docs/tutorials/07_pegasos_qsvc.ipynb
Labels: stable backport potential
