Repository qiskit-community/qiskit-machine-learning, pull requests merged in 2022-11, with the labels that each got.

#510 Remove sphinx_rtd_theme from CI
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
Labels: automerge, type: ci

#501 Updated tutorials
  .pylintdict
  docs/tutorials/01_neural_networks.ipynb
  docs/tutorials/02_neural_network_classifier_and_regressor.ipynb
  docs/tutorials/02a_training_a_quantum_model_on_a_real_dataset.ipynb
  docs/tutorials/05_torch_connector.ipynb
  docs/tutorials/09_saving_and_loading_models.ipynb
  docs/tutorials/11_qcnn_initial_point.json
  docs/tutorials/11_quantum_convolutional_neural_networks.ipynb
Labels: documentation

#509 Update documentation
  .github/workflows/main.yml
  .pylintdict
  README.md
  docs/index.rst
  docs/migration/01_migration_guide_0.5.ipynb
  docs/migration/index.rst
  qiskit_machine_learning/algorithms/__init__.py
  qiskit_machine_learning/algorithms/classifiers/neural_network_classifier.py
  qiskit_machine_learning/algorithms/classifiers/pegasos_qsvc.py
  qiskit_machine_learning/algorithms/classifiers/qsvc.py
  qiskit_machine_learning/algorithms/classifiers/vqc.py
  qiskit_machine_learning/algorithms/objective_functions.py
  qiskit_machine_learning/algorithms/regressors/neural_network_regressor.py
  qiskit_machine_learning/algorithms/regressors/qsvr.py
  qiskit_machine_learning/algorithms/regressors/vqr.py
  qiskit_machine_learning/algorithms/serializable_model.py
  qiskit_machine_learning/algorithms/trainable_model.py
  qiskit_machine_learning/circuit/library/__init__.py
  qiskit_machine_learning/connectors/__init__.py
  qiskit_machine_learning/datasets/__init__.py
  qiskit_machine_learning/kernels/__init__.py
  qiskit_machine_learning/kernels/base_kernel.py
  qiskit_machine_learning/kernels/fidelity_quantum_kernel.py
  qiskit_machine_learning/kernels/quantum_kernel.py
  qiskit_machine_learning/kernels/trainable_fidelity_quantum_kernel.py
  qiskit_machine_learning/kernels/trainable_kernel.py
  qiskit_machine_learning/neural_networks/__init__.py
  qiskit_machine_learning/runtime/__init__.py
  qiskit_machine_learning/utils/__init__.py
  qiskit_machine_learning/utils/loss_functions/__init__.py
Labels: documentation

#517 Fix formatting in 02a Training a Quantum Model on a Real Dataset
  docs/tutorials/02a_training_a_quantum_model_on_a_real_dataset.ipynb
Labels: stable backport potential, documentation

#478 Tutorial for Quantum Autoencoder to compress quantum states
  .pylintdict
  docs/tutorials/12_qae_initial_point.json
  docs/tutorials/12_quantum_autoencoder.ipynb
Labels: stable backport potential, documentation

#521 Remove previously deprecated datasets
  qiskit_machine_learning/datasets/__init__.py
  qiskit_machine_learning/datasets/breast_cancer.py
  qiskit_machine_learning/datasets/digits.py
  qiskit_machine_learning/datasets/gaussian.py
  qiskit_machine_learning/datasets/iris.py
  qiskit_machine_learning/datasets/wine.py
  releasenotes/notes/remove-datasets-495a57011b14ccd7.yaml
  test/datasets/__init__.py
  test/datasets/breast_cancer_ref.json
  test/datasets/digits_ref.json
  test/datasets/iris_ref.json
  test/datasets/test_breast_cancer.py
  test/datasets/test_digits.py
  test/datasets/test_gaussian.py
  test/datasets/test_iris.py
  test/datasets/test_wine.py
  test/datasets/wine_ref.json
Labels: Changelog: Removal

#524 Ignore untagged reno notes on documentation
  tools/ignore_untagged_notes.sh
Labels: stable backport potential, automerge, type: ci

#523 Grammar Fixes
  docs/tutorials/01_neural_networks.ipynb
Labels: documentation

#528 remove ENHANCEMENT_REQUEST issue template
  .github/ISSUE_TEMPLATE/ENHANCEMENT_REQUEST.yaml
Labels: automerge

#531 Update docs to use new sphinx theme
  .github/workflows/main.yml
  docs/_templates/layout.html
  docs/conf.py
  requirements-dev.txt
Labels: stable backport potential, type: documentation, automerge
