Repository qiskit-community/qiskit-machine-learning, pull requests merged in 2022-09, with the labels that each got.

#457 perf: ad_hoc_data: Speed up matrix exponentiation
  qiskit_machine_learning/datasets/ad_hoc.py
Labels: Community PR

#469 Fix CI errors
  .github/actions/install-main-dependencies/action.yml
  qiskit_machine_learning/algorithms/distribution_learners/qgan/quantum_generator.py
Labels: priority: high, type: ci

#471 Use Aer package qiskit_aer
  docs/tutorials/01_neural_networks.ipynb
  docs/tutorials/02_neural_network_classifier_and_regressor.ipynb
  docs/tutorials/02a_training_a_quantum_model_on_a_real_dataset.ipynb
  docs/tutorials/05_torch_connector.ipynb
  docs/tutorials/06_torch_runtime.ipynb
  docs/tutorials/08_quantum_kernel_trainer.ipynb
  docs/tutorials/09_saving_and_loading_models.ipynb
  docs/tutorials/10_effective_dimension.ipynb
  docs/tutorials/11_quantum_convolutional_neural_networks.ipynb
  requirements-dev.txt
  test/algorithms/classifiers/test_neural_network_classifier.py
  test/algorithms/classifiers/test_vqc.py
  test/algorithms/regressors/test_neural_network_regressor.py
  test/algorithms/regressors/test_vqr.py
  test/circuit/library/test_raw_feature_vector.py
  test/connectors/test_torch.py
  test/neural_networks/test_circuit_qnn.py
  test/neural_networks/test_effective_dimension.py
  test/neural_networks/test_opflow_qnn.py
  test/neural_networks/test_two_layer_qnn.py
Labels: type: enhancement, run_slow

#476 Pin sphinx < 5.2.0
  requirements-dev.txt
Labels: priority: critical, type: bug, type: documentation

#477 Unpin sphinx
  requirements-dev.txt
Labels: type: documentation

#479 Fixed mypy latest release errors
  qiskit_machine_learning/kernels/quantum_kernel.py
  requirements-dev.txt
  test/test_deprecation.py
Labels: priority: critical, automerge

#480 Deprecate TorchRuntimeClient
  .pylintdict
  docs/tutorials/06_torch_runtime.ipynb
  qiskit_machine_learning/runtime/hookbase.py
  qiskit_machine_learning/runtime/torch_runtime_client.py
  releasenotes/notes/deprecate-torch-runtime-9bcc9270326d68d1.yaml
Labels: Changelog: Deprecation
