Repository qiskit-community/qiskit-machine-learning, pull requests merged in 2022-01, with the labels that each got.

#282 Fix copyright check when rebasing
  tools/check_copyright.py
Labels: stable backport potential, type: bug, automerge, type: ci

#285 Add support for Python 3.10
  .github/workflows/main.yml
  pyproject.toml
  releasenotes/notes/add-python310-support-b2a9435d27a4164f.yaml
  setup.py
  tox.ini
Labels: type: enhancement

#294 Pin Windows CI version to 2019
  .github/actions/install-main-dependencies/action.yml
  .github/workflows/main.yml
Labels: priority: high, type: ci

#300 [Stable] Fix deprecation of UniformDistribution in the QGAN tutorial
  docs/tutorials/04_qgans_for_loading_random_distributions.ipynb
  qiskit_machine_learning/algorithms/classifiers/pegasos_qsvc.py
  test/datasets/test_digits.py
Labels: priority: critical, type: bug

#299 Fix deprecation of UniformDistribution in the QGAN tutorial
  docs/tutorials/04_qgans_for_loading_random_distributions.ipynb
Labels: automerge
