Repository qiskit-community/qiskit-machine-learning, pull requests merged in 2022-04, with the labels that each got.

#362 Remove usage of the "l2" loss in the tutorial
  docs/tutorials/02_neural_network_classifier_and_regressor.ipynb
Labels: stable backport potential

#361 Remove deprecations and deprecate unused CrossEntropySigmoidLoss
  qiskit_machine_learning/algorithms/trainable_model.py
  qiskit_machine_learning/utils/loss_functions/loss_functions.py
  releasenotes/notes/remove-deprecation-deprecate-sigmoid-319213068ae00ea9.yaml
Labels: Changelog: Deprecation, Changelog: Removal

#368 Add tox env. gpu-amd for GPU linux tests with AMD
  tox.ini
Labels: type: enhancement

#360 Add save/load methods to the algorithms
  .pylintdict
  docs/tutorials/09_saving_and_loading models.ipynb
  qiskit_machine_learning/algorithms/__init__.py
  qiskit_machine_learning/algorithms/classifiers/pegasos_qsvc.py
  qiskit_machine_learning/algorithms/classifiers/qsvc.py
  qiskit_machine_learning/algorithms/regressors/qsvr.py
  qiskit_machine_learning/algorithms/serializable_model.py
  qiskit_machine_learning/algorithms/trainable_model.py
  releasenotes/notes/save-load-models-668cf965a9bb9875.yaml
  test/algorithms/classifiers/test_neural_network_classifier.py
  test/algorithms/classifiers/test_pegasos_qsvc.py
  test/algorithms/classifiers/test_qsvc.py
  test/algorithms/regressors/test_neural_network_regressor.py
  test/algorithms/regressors/test_qsvr.py
Labels: Changelog: New Feature

#380 Set sphinx-build --keep-going by default
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
  Makefile
  docs/Makefile
  tox.ini
Labels: type: enhancement, type: documentation

#376 Remove legacy providers interface
  .pylintdict
  qiskit_machine_learning/algorithms/distribution_learners/qgan/qgan.py
  qiskit_machine_learning/kernels/quantum_kernel.py
  qiskit_machine_learning/neural_networks/circuit_qnn.py
  qiskit_machine_learning/neural_networks/opflow_qnn.py
  qiskit_machine_learning/neural_networks/two_layer_qnn.py
  releasenotes/notes/basebackend-3b582ad521e6aa91.yaml
Labels: priority: critical

#364 Add Effective Dimension class
  .pylintdict
  qiskit_machine_learning/algorithms/__init__.py
  qiskit_machine_learning/neural_networks/__init__.py
  qiskit_machine_learning/neural_networks/effective_dimension.py
  releasenotes/notes/add-effective-dimension-class-44fd7661f6ba4b33.yaml
  test/neural_networks/test_effective_dimension.py
Labels: Changelog: New Feature

#386 Cache Terra/Aer wheel files in the CI
  .github/actions/install-main-dependencies/action.yml
  .github/workflows/main.yml
Labels: type: enhancement, type: ci

#388 Cache pip env.cache in the CI
  .github/workflows/main.yml
Labels: type: enhancement, type: ci
