Repository qiskit-community/qiskit-machine-learning, pull requests merged in 2023-10, with the labels that each got.

#696 Improve unit test temp file usage
  test/algorithms/regressors/test_fidelity_quantum_kernel_qsvr.py
  test/algorithms/regressors/test_qsvr.py
Labels: automerge

#697 Move methods into class pages for docs
  docs/_templates/autosummary/class.rst
  docs/_templates/autosummary/class_no_inherited_members.rst
Labels: automerge

#698 Used trusted publisher for PyPi
  .github/workflows/deploy-code.yml
Labels: automerge, type: ci

#700 Use cross-references to Terra and QML objects in docstrings
  qiskit_machine_learning/algorithms/classifiers/pegasos_qsvc.py
  qiskit_machine_learning/algorithms/classifiers/qsvc.py
  qiskit_machine_learning/algorithms/classifiers/vqc.py
  qiskit_machine_learning/algorithms/regressors/qsvr.py
  qiskit_machine_learning/datasets/ad_hoc.py
  qiskit_machine_learning/kernels/fidelity_statevector_kernel.py
  qiskit_machine_learning/utils/adjust_num_qubits.py
  qiskit_machine_learning/utils/loss_functions/kernel_loss_functions.py
Labels: documentation

#703 Typo in 05_torch_connector.ipynb
  docs/tutorials/05_torch_connector.ipynb
Labels: automerge, documentation
