Repository qiskit-community/qiskit-machine-learning, pull requests merged in 2023-03, with the labels that each got.

#565 Kernel PCA section added to the Quantum Kernel tutorial
  .pylintdict
  docs/tutorials/03_quantum_kernel.ipynb
Labels: QAMP, documentation

#568 Update slack invite link
  README.md
Labels: automerge

#581 deploy documentation in qiskit.org/ecosystem
  tools/deploy_documentation.sh
Labels: stable backport potential, type: documentation, automerge, type: ci

#589 Add jupyter as requirements to testenv:gettext in tox.ini
  tox.ini
Labels: stable backport potential

#590 Fix reno formatting
  releasenotes/notes/0.6/add-callable-optimizer-75a05eebbd93530b.yaml
Labels: stable backport potential, automerge
