Repository qiskit-community/qiskit-machine-learning, pull requests merged in 2023-05, with the labels that each got.

#610 Pin ipython
  constraints.txt
Labels: stable backport potential

#612 Remove a language from versionutils
  docs/versionutils.py
Labels: stable backport potential, type: documentation

#614 Update doc links and remove mailmap info from readme
  README.md
Labels: automerge

#616 Use seeded rng to generate regressor test data
  test/algorithms/regressors/test_neural_network_regressor.py
  test/algorithms/regressors/test_neural_network_regressor_estimator_qnn.py
  test/algorithms/regressors/test_vqr.py
  test/algorithms/regressors/test_vqr_estimator_qnn.py
Labels: type: ci

#512 Add support for Python 3.11
  .github/workflows/main.yml
  .pylintrc
  constraints.txt
  pyproject.toml
  releasenotes/notes/add-python311-support-5b71a67a07606405.yaml
  requirements-dev.txt
  requirements.txt
  setup.py
  test/connectors/test_torch.py
  test/connectors/test_torch_connector.py
  test/connectors/test_torch_networks.py
  test/kernels/test_fidelity_qkernel.py
  test/kernels/test_fidelity_statevector_kernel.py
  test/kernels/test_new_vs_old_kernel.py
  test/kernels/test_new_vs_old_kernel_sv.py
  test/neural_networks/test_effective_dimension.py
  test/neural_networks/test_effective_dimension_primitives.py
  test/neural_networks/test_estimator_qnn.py
  test/utils/test_adjust_num_qubits.py
  tools/check_copyright.py
  tools/find_gpu_decorated_methods.py
  tox.ini
Labels: stable backport potential, type: enhancement

#619 Fix language toggle in docs
  docs/_templates/page.html
  docs/_templates/versions.html
  docs/conf.py
  docs/versionutils.py
  requirements-dev.txt
Labels: stable backport potential, type: documentation

#621 Terra main vs stable install switch
  .github/actions/install-main-dependencies/action.yml
  .github/workflows/main.yml
Labels: stable backport potential

#626 Remove unused custom CSS files and Sphinx directives
  docs/_static/custom.css
  docs/_static/gallery.css
  docs/_static/style.css
  docs/conf.py
  docs/custom_directives.py
  requirements-dev.txt
Labels: stable backport potential, automerge, documentation

#628 Remove the `includenodoc` and `customcarditem` directives
  docs/conf.py
  docs/custom_directives.py
Labels: stable backport potential, type: documentation, automerge

#645 Fix a matplotlib deprecation message in 08_quantum_kernel_trainer.ipynb tutorial
  docs/tutorials/08_quantum_kernel_trainer.ipynb
Labels: stable backport potential, documentation

#647 Add project urls to setup
  setup.py
Labels: stable backport potential, automerge
