Repository qiskit-community/qiskit-machine-learning, pull requests merged in 2024-12, with the labels that each got.

#862 [Docs] Fix TOCs and update QNN derived primitives
  .pylintdict
  docs/apidocs/qiskit_machine_learning.gradients.rst
  docs/apidocs/qiskit_machine_learning.optimizers.rst
  docs/apidocs/qiskit_machine_learning.state_fidelities.rst
  qiskit_machine_learning/__init__.py
  qiskit_machine_learning/algorithms/__init__.py
  qiskit_machine_learning/algorithms/trainable_model.py
  qiskit_machine_learning/circuit/library/__init__.py
  qiskit_machine_learning/connectors/__init__.py
  qiskit_machine_learning/datasets/__init__.py
  qiskit_machine_learning/gradients/__init__.py
  qiskit_machine_learning/neural_networks/__init__.py
  qiskit_machine_learning/neural_networks/estimator_qnn.py
  qiskit_machine_learning/neural_networks/sampler_qnn.py
  qiskit_machine_learning/optimizers/__init__.py
  qiskit_machine_learning/optimizers/optimizer_utils/__init__.py
  qiskit_machine_learning/optimizers/spsa.py
  qiskit_machine_learning/state_fidelities/__init__.py
Labels: stable backport potential, documentation 📖

#875 Restore latest Qiskit 1.3+
  constraints.txt
Labels: stable backport potential, on hold 🛑, dependencies 🔗

#879 Extended support for different V2 transpilers from different backends.
  qiskit_machine_learning/neural_networks/estimator_qnn.py
  qiskit_machine_learning/neural_networks/sampler_qnn.py
Labels: priority: high, stable backport potential, type: enhancement ✨

#878 Fix callback compatibility for trainable_model
  qiskit_machine_learning/algorithms/trainable_model.py
  releasenotes/notes/fix-callback-trainable_model-ca52060260a3e466.yaml
  test/algorithms/classifiers/test_neural_network_classifier.py
  test/algorithms/regressors/test_neural_network_regressor.py
Labels: Changelog: Bugfix, priority: high, stable backport potential

#884 Update migration guide
  docs/migration/02_migration_guide_0.8.rst
Labels: stable backport potential, documentation 📖

#886 Update `SamplerQNN` docs
  qiskit_machine_learning/neural_networks/sampler_qnn.py
Labels: stable backport potential, type: documentation 📖
