Repository qiskit-community/qiskit-machine-learning, pull requests merged in 2024-01, with the labels that each got.

#733 Workaround CI failure with nbconvert version pin
  constraints.txt
Labels: stable backport potential, automerge

#728 Fix QNN for input and weights ordering
  docs/tutorials/11_qcnn_initial_point.json
  docs/tutorials/11_quantum_convolutional_neural_networks.ipynb
  qiskit_machine_learning/neural_networks/estimator_qnn.py
  qiskit_machine_learning/neural_networks/neural_network.py
  qiskit_machine_learning/neural_networks/sampler_qnn.py
  releasenotes/notes/fix_qnn_binding_order-74caef8a49ecffe5.yaml
  test/neural_networks/test_estimator_qnn.py
Labels: stable backport potential, automerge

#737 Fix copyright dates from PR #728 for 2024
  qiskit_machine_learning/neural_networks/estimator_qnn.py
  qiskit_machine_learning/neural_networks/neural_network.py
  qiskit_machine_learning/neural_networks/sampler_qnn.py
  test/neural_networks/test_estimator_qnn.py
Labels: stable backport potential, automerge

#739 Deploy docs to GitHub Pages
  .github/workflows/deploy-docs.yml
  docs/conf.py
  tools/deploy_documentation.sh
  tools/deploy_translatable_strings.sh
  tools/github_poBranch_update_key.enc
  tools/rclone.conf.enc
  tox.ini
Labels: stable backport potential

#743 The deprecated calling sytle of circut draw function has been updated in tutorials.
  docs/tutorials/01_neural_networks.ipynb
  docs/tutorials/02_neural_network_classifier_and_regressor.ipynb
  docs/tutorials/02a_training_a_quantum_model_on_a_real_dataset.ipynb
  docs/tutorials/04_torch_qgan.ipynb
  docs/tutorials/05_torch_connector.ipynb
  docs/tutorials/10_effective_dimension.ipynb
  docs/tutorials/12_quantum_autoencoder.ipynb
Labels: stable backport potential

#748 Add dependabot to manage Github Actions update
  .github/dependabot.yml
Labels: automerge, type: ci

#755 Update upload/download-artifact actions versions
  .github/actions/install-main-dependencies/action.yml
  .github/workflows/deploy-code.yml
  .github/workflows/main.yml
Labels: stable backport potential
