Repository qiskit-community/qiskit-machine-learning, pull requests merged in 2024-02, with the labels that each got.

#761 Make MockFidelity also compatible with Qiskit Algorithms >= 0.3.0
  test/kernels/test_fidelity_qkernel.py
Labels: stable backport potential, type: ci

#763 Remove most qiskit.org links
  CONTRIBUTING.md
  README.md
  docs/getting_started.rst
  docs/migration/01_migration_guide_0.5.rst
  docs/tutorials/01_neural_networks.ipynb
  docs/tutorials/02a_training_a_quantum_model_on_a_real_dataset.ipynb
  docs/tutorials/03_quantum_kernel.ipynb
  docs/tutorials/04_torch_qgan.ipynb
  docs/tutorials/05_torch_connector.ipynb
  qiskit_machine_learning/algorithms/trainable_model.py
  setup.py
Labels: stable backport potential, type: documentation

#764 Remove qiskit.org links from release notes
  releasenotes/notes/0.7/migrate-algorithms-d96866989800aa91.yaml
  releasenotes/notes/0.7/remove-deprecated-3c8493dd0b92c4a3.yaml
  releasenotes/notes/0.7/remove-qgan-runtime-aa74bec5d95ffa00.yaml
Labels: automerge

#769 Fix tutorials to work with Qiskit 1.0
  docs/tutorials/01_neural_networks.ipynb
  docs/tutorials/02_neural_network_classifier_and_regressor.ipynb
  docs/tutorials/02a_training_a_quantum_model_on_a_real_dataset.ipynb
  docs/tutorials/03_quantum_kernel.ipynb
  docs/tutorials/04_torch_qgan.ipynb
  docs/tutorials/05_torch_connector.ipynb
  docs/tutorials/07_pegasos_qsvc.ipynb
  docs/tutorials/08_quantum_kernel_trainer.ipynb
  docs/tutorials/09_saving_and_loading_models.ipynb
  docs/tutorials/10_effective_dimension.ipynb
  docs/tutorials/11_quantum_convolutional_neural_networks.ipynb
  docs/tutorials/12_quantum_autoencoder.ipynb
  docs/tutorials/tutorial_magics.py
Labels: stable backport potential, type: documentation

#774 Add Python 3.12 support
  .github/workflows/main.yml
  releasenotes/notes/py_3_12_support-6ac8bce3652299fb.yaml
  setup.py
  tox.ini
Labels: stable backport potential, type: ci

#772 Added max_circuits_per_job and removed deepcopy dependency of the quantum kernel trainer fixing #701 and #600
  qiskit_machine_learning/kernels/algorithms/quantum_kernel_trainer.py
  qiskit_machine_learning/kernels/fidelity_quantum_kernel.py
  releasenotes/notes/fix-701-max_circuits_per_job-and-600-deepcopy-dependency-e6eda2e5b986c1be.yaml
  test/kernels/test_fidelity_qkernel.py
Labels: stable backport potential

#778 Bug/607 fidelity statevector kernel cannot be pickled
  qiskit_machine_learning/kernels/fidelity_statevector_kernel.py
  releasenotes/notes/fix-fid_statevector_kernel-pickling-b7fa2b13a15ec9c6.yaml
  test/kernels/test_fidelity_statevector_kernel.py
Labels: stable backport potential
